In [1]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import time
from scipy.optimize import minimize
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_excel("Устойчивост эл_сети.xlsx",engine='openpyxl',sheet_name='Data_for_UCI_named')

In [3]:
df.tail()

tau1      tau2      tau3      tau4        p1        p2        p3  \
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4      stab     stabf  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  0.023892  unstable  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120 -0.025803    stable  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984 -0.031810    stable  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  0.037789  unstable  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  0.045263  unstable

In [4]:
d = {'unstable': 0, 'stable': 1}
df.stabf = df.stabf.map(d)

In [5]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab  stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347      0  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957      1  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471      0  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871      0  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860      0

In [6]:
X = df.drop(['stab', 'stabf'], axis=1).values
y = df.stabf.values

In [7]:
for i in range(X.shape[1]):
    X[:,i]=(X[:,i]-X[:,i].min())/(X[:,i].max()-X[:,i].min())

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [43]:
sc = Seniority_committee(N=500)

In [44]:
sc.fit(X_train, y_train, maxiter=20)

Making hyperplane number 1
X_train.shape[0] = 7000
Optimization is started
First approximation is obtained
Time taken for optimization: 60.499661684036255
The minimum of the loss function: -264.0
Optimization is started
First approximation is obtained
Time taken for optimization: 26.034878253936768
The minimum of the loss function: -12.178820020957273
X_1.shape[0] = 264
X_0.shape[0] = 13
Cutted data shape is not enough
Optimization is started
First approximation is obtained
Time taken for optimization: 63.74943971633911
The minimum of the loss function: -403.0
Optimization is started
First approximation is obtained
Time taken for optimization: 24.504884243011475
The minimum of the loss function: -56.72920981048451
X_1.shape[0] = 403
X_0.shape[0] = 112
Cutted data shape is not enough
Optimization is started
First approximation is obtained
Time taken for optimization: 64.373539686203
The minimum of the loss function: -475.1796716048606
Optimization is started
First approximation is obtai

First approximation is obtained
Time taken for optimization: 50.49716281890869
The minimum of the loss function: -336.5217592870665
Optimization is started
First approximation is obtained
Time taken for optimization: 25.879375219345093
The minimum of the loss function: -37.530902782616536
X_1.shape[0] = 350
X_0.shape[0] = 48
Cutted data shape is not enough
Optimization is started
First approximation is obtained
Time taken for optimization: 48.65535354614258
The minimum of the loss function: -400.1810102525392
Optimization is started
First approximation is obtained
Time taken for optimization: 26.08391571044922
The minimum of the loss function: -74.80591262891392
X_1.shape[0] = 471
X_0.shape[0] = 112
Cutted data shape is not enough
Optimization is started
First approximation is obtained
Time taken for optimization: 50.17775797843933
The minimum of the loss function: -457.05067419372494
Optimization is started
First approximation is obtained
Time taken for optimization: 22.25921249389648

First approximation is obtained
Time taken for optimization: 69.49002242088318
The minimum of the loss function: -332.0
Optimization is started
First approximation is obtained
Time taken for optimization: 84.75672364234924
The minimum of the loss function: -698.2272638423916
X_1.shape[0] = 676
X_0.shape[0] = 2100


In [48]:
optim_weights = sc.weights_hp

In [61]:
optim_weights

{1: (0,
  array([  617.43525033,   539.73595299,   485.01990141,   476.99384603,
         -2257.95095421,  -723.06823243,  -799.98288163,  -888.85836126,
           635.64094694,   596.44673478,    98.00411494,   303.59060635]),
  0.003264417845484222),
 2: (1,
  array([ -248.21422733,  -399.13967414, -1803.65310765,  -227.20625925,
          1500.33791088,   556.79677475,   600.54208049,   488.98173997,
          -806.69535206,  -802.93057197,    28.2307978 ,  -853.45366366]),
  1.0),
 3: (0,
  array([  8.81737104,  13.14315127,  23.34389129,  21.41338772,
         -62.52249616, -24.47233907, -24.70956411, -20.66899839,
          -1.20584566,   7.41496479,  17.72079434,  17.84662403]),
  0.015647226173541962),
 4: (1,
  array([-19.99798397, -44.05879675,  -0.20737807, -16.00983758,
          62.45366298,  21.49289305,  23.76742717,  24.96155423,
         -31.55335624, -12.61178314, -38.13047017, -29.47349193]),
  0.9822485207100592),
 5: (0,
  array([ 17.0575306 ,  13.2653159 ,  13.05

In [53]:
sc_1 = Seniority_committee(N=500)

In [54]:
sc_1.weights_hp = optim_weights

In [59]:
train_preds = sc_1.predict(X_train)

In [57]:
test_preds = sc_1.predict(X_test)

In [60]:
roc_auc_score(y_train, train_preds)

0.6953112577839854

In [58]:
roc_auc_score(y_test, test_preds)

0.6854070352149612

In [52]:
class Seniority_committee:
    """
        ML Algo based on the seniority committee method
    """
    
    def __init__(self, N):
        """
            :param N: число наблюдений, находящихся выше гиперплоскости
        """
        
        self.X_train = None
        self.y_train = None
        self.L = -1
        self.N = N
        self.weights_hp = dict() # здесь будут записаны оптимальные веса гиперплоскостей в виде: 
                                 # {'num_hyperplane': (voted_class, optim_weights, probability)}
        self.optim_params = dict() # здесь будут записаны параметры оптимизации гиперплоскостей в виде:
                   # {'cycle_range': int, 'disp': bool, 'adaptive': bool, 'maxiter': int or None, 'xatol': float or None}
                   # значение параметров дано в описании метода make_hyperplane
        
        
    def probability(self, X, w):
        """
            Принимает на вход матрицу фичей и вектор весов
            Возвращает предсказание вероятность того, что y = 1 при фиксированных x, P(y=1|x)

            :param X: матрица признаков 
            :param w: вектор весов
            :returns: вероятность того, что y = 1 при фиксированных x, P(y=1|x) ## вектор вероятностей = ReLU1(X.T*w)
        """
        
        linear = np.dot(X, w)
        linear[linear < 0] = 0
        linear[linear > 1] = 1
        
        return linear
    
    
    def compute_loss(self, X, y, w):
        """
            Принимает на вход матрицу весов, вектор ответов, вектор весов и параметр L, 
            влияющий на долю класса 0 в отсекающей гиперплоскости.
            Выдаёт на выход значение функции потерь
            
            :param X: матрица признаков
            :param w: вектор целевой переменной
            :param w: вектор весов
            :returns: значение функции потерь
        """
        
        p1 = self.probability(X, w)
        loss = np.sum((self.L - (self.L + 1) * y) * p1)
        
        return loss
    
    
    def compute_train_loss_class_0(self, w):
        """
            Function that we want to minimize, the committee member votes for class 1
            
            :param w: вектор весов
            :returns: значение функции потерь на обучающей выборке, когда член коммитета голосует за класс 0
        """
        
        if self.X_train is None or self.y_train is None:
            raise Exception('Model is not fitted')
        
        return self.compute_loss(self.X_train, 1 - self.y_train, w)
    
    
    def compute_train_loss_class_1(self, w):
        """
            Function that we want to minimize, the committee member votes for class 1
            
            :param w: вектор весов
            :returns: значение функции потерь на обучающей выборке, когда член коммитета голосует за класс 1
        """
        
        if self.X_train is None or self.y_train is None:
            raise Exception('Model is not fitted')
        
        return self.compute_loss(self.X_train, self.y_train, w)
    
    
    def make_hyperplane(self, class_num, X_train, c=0.1, cycle_range=100, disp=False, \
                        adaptive=True, maxiter=None, xatol=None):
        """
            Function that makes one of three hyperplanes
            
            :param class_num: класс, за который голосует данный член комитета: [0, 1]
            :param X_train: матрица признаков обучающей выборки
            :param с: вспомогательный коэффициент для выбора начального приближения
            :param cycle_range: количество итераций минимизации функции потерь
            Параметры оптимизации с помощью алгоритма Нелдера-Мида:
                :param disp: bool: печать сообщения о сходимости
                :param adaptive: bool: адаптация параметров алгоритма для размерности задачи (полезно при больших размерностях)
                :param maxiter: максимально допустимое количество итераций при оптимизации
                :param xatol: абсолютная ошибка на оптимальных точках между итерациями, приемлемая для сходимости
            :returns: значение функции потерь на тестовой выборке
        """
        
        if self.X_train is None or self.y_train is None:
            raise Exception('Using make_hyperplane method before fitting')
        if class_num not in [0, 1]:
            raise Exception('Only binary classification is available, class_num should be 0 or 1')
        
        optim_result = []
        optim_result_more_precise = []
        start_time = time.time()
        
        print('Optimization is started')

        for i in range(cycle_range):
            
            start_w = np.array((np.random.rand(X_train.shape[1]) - 0.5) * c)
            
            if class_num == 1:
                res = minimize(self.compute_train_loss_class_1, x0=start_w, method='Nelder-Mead', \
                               options={'disp': disp,'adaptive': adaptive, 'maxiter': maxiter, 'xatol': xatol})
            elif class_num == 0:
                res = minimize(self.compute_train_loss_class_0, x0=start_w, method='Nelder-Mead', \
                               options={'disp': disp,'adaptive': adaptive, 'maxiter': maxiter, 'xatol': xatol})
#             if res.fun < 0:
            optim_result.append(res.x)
            
        
        if optim_result == []:
            raise Exception('We\'ve not get any satisfying first approximation')

        print('First approximation is obtained')
        
        for start_w_new in optim_result:
            
            if class_num == 1:
                res = minimize(self.compute_train_loss_class_1, x0=start_w_new, method='Nelder-Mead', \
                         options={'disp': False, 'adaptive':True, 'xatol':1})
            elif class_num == 0:
                res = minimize(self.compute_train_loss_class_0, x0=start_w_new, method='Nelder-Mead', \
                         options={'disp': False, 'adaptive':True, 'xatol':1})

            for k in range(2):
                if class_num == 1:
                    res = minimize(self.compute_train_loss_class_1, x0=res.x, method='Nelder-Mead', \
                             options={'disp': False, 'adaptive':True})
                elif class_num == 0:
                    res = minimize(self.compute_train_loss_class_0, x0=res.x, method='Nelder-Mead', \
                             options={'disp': False, 'adaptive':True})

            optim_result_more_precise += [[res.fun, res.x]]

        optim_result_more_precise = pd.DataFrame(optim_result_more_precise)
        optim_result_more_precise = optim_result_more_precise.sort_values(0).head(1)
        hyperplane_coefficients = optim_result_more_precise[1].values[0]
        print('Time taken for optimization: {0}'.format(time.time() - start_time))
        print('The minimum of the loss function: {0}'.format(optim_result_more_precise[0].values[0]))

        return hyperplane_coefficients
        
    
    def cutter(self, X, w):
        """
            Function that makes binary targets for rational numbers
            
            :param X: матрица признаков
            :param w: вектор оптимальных весов
            :returns: бинаризованные предсказания целевой переменной
        """
        
        linear = np.dot(X, w)
        linear[linear < 0] = 0
        
        return np.sign(linear)
    
    
    def fit(self, X, y, cycle_range=100, disp=False, adaptive=True, maxiter=10, xatol=0.3):
        """
            Fits the algorithm on the train sample 
            
            :param X: матрица признаков, обучающая выборка
            :param y: вектор истинных значений целевой переменной обучающей выборки
            Параметры оптимизации с помощью алгоритма Нелдера-Мида:
                :param disp: bool: печать сообщения о сходимости
                :param adaptive: bool: адаптация параметров алгоритма для размерности задачи (полезно при больших размерностях)
                :param maxiter: максимально допустимое количество итераций при оптимизации
                :param xatol: абсолютная ошибка на оптимальных точках между итерациями, приемлемая для сходимости
            :returns: -, но на выходе обученная моделька
        """
        
        self.X_train = X
        self.y_train = y
        self.optim_params = {'cycle_range': cycle_range, 'disp': disp, 'adaptive': adaptive, \
                             'maxiter': maxiter, 'xatol': xatol}
        
        hp_num = 1
        
        while self.X_train.shape[0] > 2 * self.N:
            
            print('Making hyperplane number {}'.format(hp_num))
            print('X_train.shape[0] = {}'.format(self.X_train.shape[0]))
            
            k = 10
            
            while True:
                
                print('k = {}'.format(k))
                
                self.L = 2 ** k
                
                print('L = {}'.format(L))
                
                print('Optimizing hyperplane for class 1')
                
                hp_weights_class_1 = self.make_hyperplane(class_num=1, X_train=self.X_train, \
                                                     c=0.1, cycle_range=self.optim_params['cycle_range'], \
                                                     disp=self.optim_params['disp'], \
                                                     adaptive=self.optim_params['adaptive'], \
                                                     maxiter=self.optim_params['maxiter'], \
                                                     xatol=self.optim_params['xatol'])
                
                print('Optimizing hyperplane for class 0')
                
                hp_weights_class_0 = self.make_hyperplane(class_num=0, X_train=self.X_train, \
                                                     c=0.1, cycle_range=self.optim_params['cycle_range'], \
                                                     disp=self.optim_params['disp'], \
                                                     adaptive=self.optim_params['adaptive'], \
                                                     maxiter=self.optim_params['maxiter'], \
                                                     xatol=self.optim_params['xatol'])
                
                cut_1 = self.cutter(self.X_train, hp_weights_class_1)
                cut_0 = self.cutter(self.X_train, hp_weights_class_0)
                X_1 = self.X_train[cut_1 == 1]
                y_1 = self.y_train[cut_1 == 1]
                X_0 = self.X_train[cut_0 == 1]
                y_0 = self.y_train[cut_0 == 1]
                
                print('X_1.shape[0] = {}'.format(X_1.shape[0]))
                print('X_0.shape[0] = {}'.format(X_0.shape[0]))
                
                if X_1.shape[0] < self.N and X_0.shape[0] < self.N:
                    
                    print('Cutted data shape is not enough\n')
                    k -= 1
                    continue
                    
                else:
                    
                    if X_1.shape[0] >= X_0.shape[0]:
                        
                        proba = y_1.sum() / len(y_1)
                        self.weights_hp[hp_num] = (1, hp_weights_class_1, proba)
                        
                        self.X_train = self.X_train[cut_1 == 0]
                        self.y_train = self.y_train[cut_1 == 0]
                        
                    elif X_1.shape[0] < X_0.shape[0]:
                        
                        proba = y_0.sum() / len(y_0)
                        self.weights_hp[hp_num] = (0, hp_weights_class_0, proba)
                        
                        self.X_train = self.X_train[cut_0 == 0]
                        self.y_train = self.y_train[cut_0 == 0]
                        
                    hp_num += 1
                    print()
                    break
                

    def predict(self, X):
        """
            Makes predict_proba for the sample
            
            :param X: матрица признаков, обучающая выборка
            :returns: предсказания вероятностей отнесения к классу 1
        """
        test_ = X.copy()
        
        if self.weights_hp == {}:
            raise Exception('Model is not fitted')
        
        predictions = pd.DataFrame({'proba': np.zeros(X.shape[0]), 'is_scored': False})
        
        for hp_num in self.weights_hp.keys():
            
            class_num, weights, proba = self.weights_hp[hp_num]
            
            cut = self.cutter(test_, weights)
            
            X_ = test_[cut == 1]
            test_ = test_[cut == 0]
            
            k = 0
            for i in range(predictions.shape[0]):
                
                if predictions.loc[i, 'is_scored'] == False:
                    if cut[k] == True:
                        predictions.loc[i, 'proba'] = proba
                        predictions.loc[i, 'is_scored'] = True
                    k += 1
                    
        return predictions['proba'].values